{{- if .Values.mongodb.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rig.fullname" . }}-mongodb
  labels: {{ include "rig.mongodb.labels" . | nindent 4 }}
data:
  init.js: |
    db.createUser(
      {
        user: "mongodb",
        pwd: "mongodb",
        roles: [ 
            { role: "readWrite", db: "rig" },
        ]
      }
    );
{{- end -}}
