version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: rig
    networks:
      - rig
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - ./mongodb.js:/docker-entrypoint-initdb.d/mongodb.js:ro

  minio:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /data
    networks:
      - rig
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data

  rig:
    container_name: "rig"
    depends_on:
      - mongodb
      - minio
    image: ghcr.io/rigdev/rig:dev
    build:
      dockerfile: build/package/Dockerfile
      context: ../../
    ports:
      - "4747:4747"
      - "5001:5001"
    environment:
      - RIG_CLIENT_MONGO_HOST=mongodb:27017
      - RIG_CLIENT_MONGO_USER=mongodb
      - RIG_CLIENT_MONGO_PASSWORD=mongodb
      - RIG_CLIENT_MINIO_ENDPOINT=minio:9000
      - RIG_REPOSITORY_STORAGE_STORE=mongodb
      - RIG_REPOSITORY_CAPSULE_STORE=mongodb
      - RIG_REPOSITORY_CREDENTIAL_STORE=mongodb
      - RIG_REPOSITORY_GROUP_STORE=mongodb
      - RIG_REPOSITORY_USER_STORE=mongodb
      - RIG_REPOSITORY_SESSION_STORE=mongodb
      - RIG_REPOSITORY_PROJECT_STORE=mongodb
      - RIG_REPOSITORY_DATABASE_STORE=mongodb
      - RIG_REPOSITORY_SECRET_STORE=mongodb

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../configs/server-config.yaml:/etc/rig/server-config.yaml

    networks:
      - rig
      - default

  rig-service:
    scale: 0
    image: ghcr.io/rigdev/rig:0.1.0
    command: rig-proxy

networks:
  rig:
    external: true
volumes:
  mongodb-data:
  minio-data:
